# Generated by Django 4.2.5 on 2023-10-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='buttons',
            field=models.ManyToManyField(blank=True, related_name='posts', to='bots.buttons', verbose_name='Кнопки'),
        ),
    ]
