# Generated by Django 4.2.5 on 2023-10-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_alter_post_buttons'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=12, help_text='Используется только для удобства администрирования', max_length=255, verbose_name='Название поста'),
            preserve_default=False,
        ),
    ]
