# Generated by Django 4.2.5 on 2023-10-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.CharField(help_text='Идентификатор, используется для указания следующего поста', max_length=255, unique=True, verbose_name='Custom ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='default_next_integer',
            field=models.CharField(blank=True, help_text='Идентификатор следующего поста', max_length=255, null=True, verbose_name='Next ID'),
        ),
    ]
