# Generated by Django 4.2.5 on 2023-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_post_count_alter_post_default_next_integer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.CharField(help_text='Идентификатор, используется для указания следующего поста', max_length=15, unique=True, verbose_name='Custom ID'),
        ),
    ]
