# Generated by Django 4.2.5 on 2023-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='username',
            field=models.CharField(default=1, help_text='username, использующийся для поиска в telegram', max_length=255, verbose_name='Имя бота'),
            preserve_default=False,
        ),
    ]
