# Generated by Django 4.2.5 on 2023-10-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_remove_subscribers_current_step_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('count', 'bot')},
        ),
    ]
