# Generated by Django 4.2.5 on 2023-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_post_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.CharField(help_text='Идентификатор, используется для указания следующего поста', max_length=15, verbose_name='Custom ID'),
        ),
    ]
