# Generated by Django 4.2.5 on 2023-10-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_alter_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsteps',
            name='last_message_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Telegram API последнего сообщения'),
        ),
    ]
