# Generated by Django 4.2.5 on 2023-10-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0010_currentsteps_last_message_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsteps',
            name='last_message_id',
        ),
    ]
