# Generated by Django 4.2.5 on 2023-10-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0011_remove_currentsteps_last_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_final_post',
            field=models.BooleanField(default=False, verbose_name='Последний пост воронки'),
        ),
    ]
