# Generated by Django 4.2.5 on 2023-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_post_is_final_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsteps',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Воронка завершена'),
        ),
    ]
