# Generated by Django 4.2.5 on 2023-10-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0013_currentsteps_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='bot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='bots.bot', verbose_name='Бот'),
            preserve_default=False,
        ),
    ]
