# Generated by Django 4.2.5 on 2023-10-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0015_post_photo2_post_photo3_post_photo4_post_photo5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailings',
            name='audio',
        ),
        migrations.AddField(
            model_name='mailings',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='mailings',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
