# Generated by Django 4.2.5 on 2023-10-12 13:07

from django.db import migrations, models
import django.db.models.deletion
import manage_telegrambot.utils


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0016_remove_mailings_audio_mailings_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(verbose_name='Доставлено')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_delivery', to='bots.mailings', verbose_name='Рассылка')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailing_delivery', to='bots.subscribers', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Доставка рассылки',
                'verbose_name_plural': 'Доставка рассылки',
            },
            bases=(manage_telegrambot.utils.CustomStr, models.Model),
        ),
    ]
